[package]
name = "nahoy3"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.7", features = ["full", "provider-anvil-node"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
futures-util = "0.3"
